export type Topic={id:string;icon:string;title:string;short:string;textbook:string;real:string;explain:string;situation:string;prompt:string;choices:string[];correct:number;wrong:string;challenge:string;examples:string[];hint:string};
export const topics:Topic[]=[
{id:'travel',icon:'✈',title:'Travel & Tourism',short:'Hotels, airports and asking for information.',textbook:'I would like to book a hotel room.',real:'I’d like to book a room.',explain:'Both are correct. The second uses a contraction and is common in conversation.',situation:'You are calling a hotel. The receptionist asks: “How can I help you?”',prompt:'What would you say?',choices:['I’d like to book a room for two nights.','Room book two nights.','I booking room.'],correct:0,wrong:'Use “I’d like to + verb” for a polite request.',challenge:'The receptionist asks: “How many nights would you like to stay?”',examples:['I’d like to stay for two nights.','Two nights, please.','I want to stay for three nights.'],hint:'Say how many nights. Try “I’d like to stay for…”'},
{id:'holidays',icon:'☀',title:'Holidays & Experiences',short:'Share trips, activities and past experiences.',textbook:'I have visited this place before.',real:'I’ve been here before.',explain:'“I’ve been” is a natural way to talk about experience.',situation:'A friend asks if this is your first trip to Almaty.',prompt:'Choose a natural answer.',choices:['No, I’ve been here before.','No, I am visit before.','Before here I be.'],correct:0,wrong:'Use present perfect: “I’ve been…” for life experience.',challenge:'Tell a friend about one place you have visited.',examples:['I’ve been to Astana twice.','I have visited Türkiye.','I’ve never been abroad.'],hint:'Use “I’ve been to…” or “I have visited…”'},
{id:'technology',icon:'⌁',title:'Technology & Social Media',short:'Digital habits and online communication.',textbook:'I use social media to communicate with my friends.',real:'I use social media to keep in touch with my friends.',explain:'“Keep in touch” is a common conversational chunk meaning stay connected.',situation:'Your friend asks: “How do you keep in touch with your friends?”',prompt:'Pick the clearest response.',choices:['We message each other online.','We touching internet.','I keep friends in phone.'],correct:0,wrong:'Use “message each other” or “keep in touch”.',challenge:'Explain one healthy rule you follow online.',examples:['I turn off notifications while studying.','I don’t share private information.','I limit my screen time.'],hint:'Begin with “I…” and describe a digital habit.'},
{id:'health',icon:'♥',title:'Health & Healthy Lifestyle',short:'Healthy habits, advice and wellbeing.',textbook:'You should exercise regularly.',real:'You should work out regularly.',explain:'“Work out” is a conversational phrasal verb for exercise.',situation:'Your friend wants to become healthier and asks for advice.',prompt:'What advice fits best?',choices:['You should work out a few times a week.','You should working every day.','You work out yesterday.'],correct:0,wrong:'After “should”, use the base verb: should work out.',challenge:'Give your friend one piece of healthy advice.',examples:['You should drink more water.','Try to get enough sleep.','You could walk after school.'],hint:'Use “You should…”, “You could…” or “Try to…”'},
{id:'education',icon:'◉',title:'Education & Future Plans',short:'School, ambitions and future choices.',textbook:'I intend to study at university.',real:'I’m planning to go to university.',explain:'“I’m planning to…” is a common way to discuss intentions.',situation:'A friend asks: “What are you planning to do after school?”',prompt:'Choose an appropriate response.',choices:['I’m planning to study engineering.','I planning study engineer.','I planned tomorrow university.'],correct:0,wrong:'Use “I’m planning to + base verb”.',challenge:'Describe one goal you have for your future.',examples:['I’m planning to go to university.','I want to become a designer.','I hope to study abroad.'],hint:'Try “I’m planning to…”, “I want to…” or “I hope to…”'},
{id:'environment',icon:'♧',title:'Environment',short:'Problems, solutions and responsible choices.',textbook:'We must protect the environment.',real:'We need to look after the planet.',explain:'“Look after” means protect or take care of something.',situation:'Your class is discussing ways to reduce waste at school.',prompt:'Choose the practical suggestion.',choices:['We could use refillable bottles.','We could throwing all plastic.','We need waste more.'],correct:0,wrong:'After “could”, use the base verb: could use/recycle/reduce.',challenge:'Suggest one action your school could take.',examples:['We could recycle more paper.','We should switch off the lights.','Let’s use less plastic.'],hint:'Use “We could…”, “We should…” or “Let’s…”'},
{id:'jobs',icon:'▣',title:'Jobs & Careers',short:'Skills, interviews and career choices.',textbook:'I am interested in this position.',real:'I’m interested in the job.',explain:'The contraction sounds natural; “job” is common in everyday speech.',situation:'You are in a short interview. The interviewer asks about your strengths.',prompt:'Which answer is suitable?',choices:['I’m organised and I work well in a team.','I am good worker maybe.','Team is working me.'],correct:0,wrong:'Use a clear adjective and a full statement about your skill.',challenge:'Say what job interests you and why.',examples:['I’d like to be a doctor because I enjoy helping people.','I’m interested in technology jobs.','I want to become a teacher.'],hint:'Use “I’d like to be…” or “I’m interested in…”'},
{id:'culture',icon:'✦',title:'Culture & Traditions',short:'Celebrations, traditions and identity.',textbook:'This tradition is important to our culture.',real:'This tradition means a lot to us.',explain:'“Means a lot” is a warm, conversational way to express importance.',situation:'An international student asks you about Nauryz.',prompt:'Choose the welcoming response.',choices:['It’s a spring celebration that means a lot to us.','It spring important us.','Nauryz was celebrate tomorrow.'],correct:0,wrong:'Use a complete present-tense sentence to explain the tradition.',challenge:'Describe one tradition that is important to you.',examples:['We celebrate Nauryz with family and friends.','This tradition means a lot to my family.','We cook traditional food together.'],hint:'Name the tradition, then say what people do or why it matters.'}
];
export const spaceTypes=['start','textbook','real','situation','challenge','bonus','mystery','textbook','real','situation','challenge','bonus','finish'] as const;
export type SpaceType=typeof spaceTypes[number];
