export type Expression={id:number;topic:string;classroom:string;textbook:string;real:string;meaning:string;register:string;situation:string;example:string};
const rows:[string,string,string,string,string,string,string][]=[
['Greetings & Small Talk','How are you?','How are you?','How’s it going?','Ask how someone is','casual','You meet a new student'],
['Greetings & Small Talk','I am fine, thank you.','I’m fine, thank you.','I’m good, thanks.','Say you are well','casual','A friend asks how you are'],
['Greetings & Small Talk','What is your name?','What’s your name?','Hey, I’m Alex. And you?','Introduce yourself','friendly','You meet someone your age'],
['Greetings & Small Talk','Where are you from?','Where are you from?','Are you from around here?','Ask about someone’s home','friendly','You start a conversation'],
['Greetings & Small Talk','Nice to meet you.','It’s nice to meet you.','Great to meet you!','Respond to an introduction','friendly','A new classmate introduces themselves'],
['Greetings & Small Talk','How was your weekend?','How was your weekend?','Did you have a good weekend?','Start small talk','casual','Monday morning at school'],
['Greetings & Small Talk','What are your hobbies?','What do you like doing?','What are you into?','Ask about interests','informal','Talking to another teenager'],
['Greetings & Small Talk','Goodbye.','See you later.','Catch you later!','End a conversation','informal','Leaving your friends'],
['Everyday Communication','Could you repeat, please?','Could you repeat that, please?','Sorry, can you say that again?','Ask someone to repeat','neutral','You did not hear a friend'],
['Everyday Communication','I do not understand.','I don’t understand.','Sorry, I didn’t get that.','Say you did not understand','neutral','Instructions are unclear'],
['Everyday Communication','Can you help me?','Could you help me, please?','Could you give me a hand?','Ask for help','neutral','You need help with a task'],
['Everyday Communication','What does this word mean?','What does this word mean?','What does that mean?','Ask for meaning','neutral','You hear an unfamiliar phrase'],
['Everyday Communication','Can you explain it again?','Could you explain that again?','Can you run through that again?','Ask for another explanation','neutral','You missed part of an explanation'],
['Everyday Communication','Please wait.','Could you wait a moment?','Hang on a sec.','Ask someone to wait','informal','You need a moment'],
['Everyday Communication','I agree with you.','I agree with you.','Yeah, exactly!','Show agreement','informal','A friend shares an opinion'],
['Everyday Communication','I disagree.','I don’t agree with that.','I’m not sure about that.','Disagree politely','neutral','A group discussion'],
['Friends & Teen Life','Do you want to come?','Would you like to come?','Wanna come?','Invite a friend','informal spoken','Making plans after school'],
['Friends & Teen Life','What are you doing?','What are you doing?','What are you up to?','Ask about plans','informal','Messaging a friend'],
['Friends & Teen Life','Let us meet later.','Let’s meet later.','Want to hang out later?','Suggest meeting','informal','Planning free time'],
['Friends & Teen Life','That is a good idea.','That’s a good idea.','Sounds good!','Accept a suggestion','informal','A friend suggests a plan'],
['Friends & Teen Life','I cannot come.','I’m afraid I can’t come.','Sorry, I can’t make it.','Decline an invitation','friendly','You already have plans'],
['Friends & Teen Life','What do you think?','What do you think?','What do you reckon?','Ask for an opinion','informal','Choosing a film'],
['Friends & Teen Life','Send me a message.','Send me a message.','Text me.','Ask someone to message','informal','Confirming plans'],
['Friends & Teen Life','I am joking.','I’m only joking.','Just kidding!','Show something was a joke','informal','Chatting with friends'],
['Shopping & Services','I would like a coffee, please.','I’d like a coffee, please.','Can I get a coffee, please?','Order a drink','neutral','At a café'],
['Shopping & Services','How much does it cost?','How much is it?','How much is this?','Ask the price','neutral','In a shop'],
['Shopping & Services','Do you have a larger size?','Do you have this in a larger size?','Have you got this in a bigger size?','Ask for another size','neutral','Shopping for clothes'],
['Shopping & Services','May I try this on?','Can I try this on?','Could I try this on?','Ask to try clothing','neutral','In a clothes shop'],
['Shopping & Services','Where is the station?','Could you tell me the way to the station?','How do I get to the station?','Ask for directions','neutral','You are in a new city'],
['Shopping & Services','I need information.','Could you give me some information?','Hi, could you help me with something?','Ask service staff for information','polite','At an information desk'],
['Shopping & Services','This is not what I ordered.','This isn’t what I ordered.','Sorry, I think I ordered something else.','Explain an order problem','polite','The server brings the wrong drink'],
['Shopping & Services','That is all, thank you.','That’s all, thank you.','That’s everything, thanks.','Finish an order','neutral','At a café counter'],
['Reactions & Emotions','That is surprising.','That’s surprising.','No way! Really?','React to surprising news','informal','A friend tells you big news'],
['Reactions & Emotions','I am very happy for you.','I’m really happy for you.','That’s amazing—I’m so happy for you!','Celebrate someone’s news','friendly','A friend shares good news'],
['Reactions & Emotions','I am sorry to hear that.','I’m sorry to hear that.','Oh no, that’s awful.','Show sympathy','friendly','Someone shares bad news'],
['Reactions & Emotions','Do not worry.','Don’t worry about it.','No worries!','Reassure someone','informal','A friend apologises'],
['Reactions & Emotions','I am excited.','I’m really excited.','I can’t wait!','Show excitement','informal','A trip is coming soon'],
['Reactions & Emotions','I am not certain.','I’m not sure.','I’m not so sure about that.','Show uncertainty','neutral','You doubt an idea'],
['Reactions & Emotions','That is unfortunate.','That’s unfortunate.','That’s a shame.','React to disappointment','friendly','Plans are cancelled'],
['Reactions & Emotions','It does not matter.','It doesn’t matter.','It’s no big deal.','Say a problem is small','informal','A friend makes a small mistake']];
export const expressions:Expression[]=rows.map((r,i)=>({id:i+1,topic:r[0],classroom:r[1],textbook:r[2],real:r[3],meaning:r[4],register:r[5],situation:r[6],example:`A: ${r[2]}\nB: ${r[3]}`}));
export const topics=['Greetings & Small Talk','Everyday Communication','Friends & Teen Life','Shopping & Services','Reactions & Emotions'];
export const missions=['Meet a new student','Talk to a friend after school','Order a drink in a café','Ask for another size in a shop','React to surprising news','Ask someone for help','Make weekend plans','Help a visitor','Explain a problem','Handle something unexpected'];
