'use client';
import { useMemo, useState } from 'react';
type Task={id:number;type:'choice'|'order'|'input';kicker:string;title:string;prompt:string;options?:string[];answer:string;hint:string};
const tasks:Task[]=[
{id:1,type:'choice',kicker:'At the café',title:'Choose the most natural reply',prompt:'Barista: “Would you like anything else?”',options:['No, I don’t like it.','That’s all, thank you.','I want nothing.'],answer:'That’s all, thank you.',hint:'Think about a polite way to finish an order.'},
{id:2,type:'order',kicker:'Getting around',title:'Build the question',prompt:'Put the words in the correct order.',options:['could','tell me','you','the way','to the station'],answer:'could you tell me the way to the station',hint:'Begin with a polite modal verb.'},
{id:3,type:'choice',kicker:'Meeting someone',title:'Keep the conversation going',prompt:'Aisha: “I’ve just moved here from Almaty.”',options:['Really? How are you finding the city?','Yes, you moved.','Where is your homework?'],answer:'Really? How are you finding the city?',hint:'Show interest and ask an open question.'},
{id:4,type:'input',kicker:'Making plans',title:'Complete the message',prompt:'“Are you free to hang out ___ Saturday?”',answer:'on',hint:'Use the preposition we put before days.'},
{id:5,type:'choice',kicker:'Asking for help',title:'Pick the polite request',prompt:'Your phone battery is dead. What do you say?',options:['Give me your charger.','Could I borrow your charger, please?','My charger is you.'],answer:'Could I borrow your charger, please?',hint:'A polite request often starts with “Could I…?”'}];
export default function Home(){
 const[index,setIndex]=useState(0),[selected,setSelected]=useState(''),[words,setWords]=useState<string[]>([]),[checked,setChecked]=useState(false),[correct,setCorrect]=useState(0),[showHint,setShowHint]=useState(false),[streak,setStreak]=useState(3);const task=tasks[index];const response=task.type==='order'?words.join(' '):selected.trim();const isRight=response.toLowerCase()===task.answer.toLowerCase();const progress=Math.round(((index+(checked?1:0))/tasks.length)*100);const remainingWords=useMemo(()=>task.type==='order'?task.options?.filter(w=>!words.includes(w))??[]:[],[task,words]);
 function reset(i:number){setIndex(i);setSelected('');setWords([]);setChecked(false);setShowHint(false)}
 function check(){if(!response||checked)return;setChecked(true);if(isRight){setCorrect(v=>v+1);setStreak(v=>v+1)}else setStreak(0)}
 function next(){if(index===tasks.length-1){reset(0);setCorrect(0)}else reset(index+1)}
 return <main className="app-shell"><header className="topbar"><a className="brand" href="#"><span className="brand-mark">S</span><span>Speak<span>Up</span></span></a><nav aria-label="Main navigation"><a className="active" href="#practice">Practice</a><a href="#situations">Situations</a><a href="#progress">My progress</a></nav><div className="header-actions"><button className="language">EN <span>⌄</span></button><button className="profile">AS</button></div></header>
 <section className="hero" id="practice"><div><p className="eyebrow">GRADE 9 · ENGLISH</p><h1>English for <em>real life.</em></h1><p className="subtitle">Practise the phrases you&apos;ll actually use — one situation at a time.</p></div><div className="week-card"><div><span>THIS WEEK</span><strong>4 <small>of 5 days</small></strong></div><div className="days">{['M','T','W','T','F'].map((d,i)=><span className={i<4?'done':''} key={i}>{i<4?'✓':d}</span>)}</div></div></section>
 <section className="workspace"><aside className="lesson-list" id="situations"><div className="section-label"><span>TODAY&apos;S PRACTICE</span><b>{progress}%</b></div><div className="progress-track"><i style={{width:`${progress}%`}}/></div>{tasks.map((t,i)=><button key={t.id} onClick={()=>reset(i)} className={`lesson ${i===index?'current':''} ${i<index?'completed':''}`}><span className="lesson-num">{i<index?'✓':String(i+1).padStart(2,'0')}</span><span><b>{t.kicker}</b><small>{t.title}</small></span><span className="arrow">›</span></button>)}<div className="streak"><span className="flame">♨</span><div><strong>{streak} day streak</strong><small>Keep it going!</small></div></div></aside>
 <article className="task-card"><div className="task-top"><span className="situation"><i>●</i> SITUATION {String(index+1).padStart(2,'0')}</span><span className="task-count">{index+1} / {tasks.length}</span></div><p className="kicker">{task.kicker}</p><h2>{task.title}</h2><div className="dialogue"><span className="avatar">☕</span><p>{task.prompt}</p></div>
 {task.type==='choice'&&<div className="options">{task.options?.map((o,i)=><button disabled={checked} onClick={()=>setSelected(o)} className={`${selected===o?'selected':''} ${checked&&o===task.answer?'right':''} ${checked&&selected===o&&!isRight?'wrong':''}`} key={o}><span>{String.fromCharCode(65+i)}</span>{o}<i>{selected===o?'●':'○'}</i></button>)}</div>}
 {task.type==='input'&&<input aria-label="Your answer" disabled={checked} className="answer-input" value={selected} onChange={e=>setSelected(e.target.value)} placeholder="Type the missing word…" onKeyDown={e=>e.key==='Enter'&&check()}/>} {task.type==='order'&&<><div className="sentence-build">{words.length?words.map(w=><button key={w} onClick={()=>!checked&&setWords(words.filter(x=>x!==w))}>{w}</button>):<span>Build your sentence here…</span>}</div><div className="word-bank">{remainingWords.map(w=><button key={w} onClick={()=>setWords([...words,w])}>{w}</button>)}</div></>}
 {checked&&<div className={`feedback ${isRight?'success':'error'}`}><strong>{isRight?'Nice work!':'Almost there'}</strong><span>{isRight?'That sounds natural and polite.':`Correct answer: “${task.answer}”`}</span></div>}<div className="task-actions"><button className="hint" onClick={()=>setShowHint(!showHint)}>💡 {showHint?task.hint:'Need a hint?'}</button>{checked?<button className="check" onClick={next}>{index===tasks.length-1?'Start again':'Next →'}</button>:<button className="check" disabled={!response} onClick={check}>Check answer</button>}</div></article>
 <aside className="side-panel" id="progress"><div className="score-card"><p>SESSION SCORE</p><div className="score"><strong>{correct}</strong><span>/{tasks.length}</span></div><small>Correct answers</small></div><div className="tip-card"><span className="quote">“</span><h3>Sound more natural</h3><p>Native speakers often use contractions: say <b>“I&apos;d like”</b> instead of <b>“I would like.”</b></p><span className="tip-tag">QUICK TIP</span></div><div className="level-card"><div><span>YOUR LEVEL</span><b>B1</b></div><p>Intermediate</p><div className="mini-track"><i/></div><small>180 XP to B1+</small></div></aside></section><footer>SpeakUp · Real English for real moments <span>Designed for Grade 9 learners</span></footer></main>}
